### ISSUE TITLE
C++ Implementation of QMagFace

### ISSUE THREAD

**Issue by sfxeazilove** [pterhoer/QMagFace#11]
Hi, I understand Qmag is a postprocessing function that works on MagFace, i would love to know if there is a c++ implementation of the process for aligning and computing embeddings.

**Comment by mihlefeld** [comment]
Hey, we use MTCNN for the alignment process and MagFace for computation of the embeddings. To my knowledge, no C++ versions for these exist at the moment. However, since PyTorch is written in C++ and has excellent C++ bindings, it is definitely possible to change that. I do believe it would take quite some time and effort though.
