### ISSUE TITLE
Why search omega > 0

### ISSUE THREAD

**Issue by Walstruzz** [pterhoer/QMagFace#7]
Hello, I understand \omega must be a negative number, so why do you search omegas = np.linspace(-max_omega, max_omega, num=weights_num)  instead of omegas = np.linspace(-max_omega, 0, num=weights_num)  here?
https://github.com/pterhoer/QMagFace/blob/395797145da1b1b263cbe7fb1564c6ea91f55b23/similarity/qmagface.py#L41

**Comment by mihlefeld** [comment]
Hey @Walstruzz, we use the variable omega as possible candidates to generate our linear regression. After linear regression we adapt the weighting function to always be <= 0. Because of this, it is actually possible to have some optimal omegas with positive values, to make sure that we don't miss any of those we have a fairly large search space. 

If you take a look at the visualization of this linear regression here: 
![](https://github.com/pterhoer/QMagFace/blob/main/OptimalQualityFunctions.png?raw=true) 
you can actually see, that some points have an optimal omega greater than 0.
